[package]
name = "kata-hexagonal"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
sha2 = "0.10.8"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
